version: '3.8'
services:
  bookslibrary-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/BooksLibrary/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=BooksLibrary
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 127.0.0.1:5455:5432
